import 'dart:io';
main() {
  int x=10;
  int y=20;
  stdout.write(x.hashCode);
  stdout.writeln('');
  stdout.write(x.isFinite);
  stdout.writeln('');
  stdout.write(x.isInfinite);
  stdout.writeln('');
  stdout.write(x.isNaN);
  stdout.writeln('');
  stdout.write(x.isNegative);
  stdout.writeln('');
  stdout.write(x.sign);
  stdout.writeln('');
  stdout.write(x.isEven);
  stdout.writeln('');
  stdout.write(x.isOdd);
  stdout.writeln('');
  stdout.write(x.abs());
  stdout.writeln('');
  stdout.write(x.ceil());
  stdout.writeln('');
  stdout.write(x.floor());
  stdout.writeln('');
  stdout.write(x.compareTo());
  stdout.writeln('');
  stdout.write(name.isEmpty);
  stdout.writeln('');
  stdout.write(name.length);
  stdout.writeln('');
}
